name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Start server
        run: npx http-server -p 8099 -a 127.0.0.1 . &
      - name: Run tests
        env:
          BASE_URL: http://127.0.0.1:8099/
        run: npx playwright test --reporter=line
