name: Deploy to Your Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            # Erstelle Zielverzeichnis falls nicht vorhanden
            mkdir -p ${{ secrets.SERVER_PATH }}
            cd ${{ secrets.SERVER_PATH }}
            
            # Git-Repository initialisieren oder aktualisieren
            if [ ! -d ".git" ]; then
              git init
              git remote add origin https://github.com/MarkusGerke/Architektour.git
            fi
            
            # Aktualisiere Code
            git fetch origin
            git reset --hard origin/main
            
            echo "Deployment erfolgreich!"
