name: Deploy to Webspace

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.WEBSPACE_SSH_KEY }}
        
    - name: Add server to known hosts
      run: |
        ssh-keyscan -H ${{ secrets.WEBSPACE_HOST }} >> ~/.ssh/known_hosts
        
    - name: Deploy to webspace
      run: |
        # Erstelle temporäres Verzeichnis für Deployment
        mkdir -p deploy_temp
        
        # Kopiere alle notwendigen Dateien (ohne .git, node_modules, etc.)
        cp -r index.html styles.css app.js data/ netlify.toml _headers _redirects deploy_temp/
        
        # Synchronisiere mit Webspace
        rsync -avz --delete \
          --exclude='.git/' \
          --exclude='node_modules/' \
          --exclude='test-results/' \
          --exclude='playwright-report/' \
          --exclude='.github/' \
          --exclude='tests/' \
          --exclude='tests-output/' \
          --exclude='deploy_temp/' \
          deploy_temp/ \
          ${{ secrets.WEBSPACE_USER }}@${{ secrets.WEBSPACE_HOST }}:${{ secrets.WEBSPACE_PATH }}
          
        # Berechtigungen setzen
        ssh ${{ secrets.WEBSPACE_USER }}@${{ secrets.WEBSPACE_HOST }} \
          "chmod -R 755 ${{ secrets.WEBSPACE_PATH }}"
          
    - name: Verify deployment
      run: |
        echo "Deployment erfolgreich abgeschlossen!"
        echo "Website sollte verfügbar sein unter: https://${{ secrets.WEBSPACE_HOST }}"
